COMPONENT_INCDIRS := src/include
COMPONENT_SRCDIRS := src

COMPONENT_VARS += SSDP_DEBUG_VERBOSE
SSDP_DEBUG_VERBOSE ?= 0
ifeq ($(SSDP_DEBUG_VERBOSE),1)
COMPONENT_CXXFLAGS += -DSSDP_DEBUG_VERBOSE=1
endif

# Major UPnP version to use
COMPONENT_VARS += UPNP_VERSION
UPNP_VERSION ?= 1.0
COMPONENT_CXXFLAGS += -DUPNP_VERSION=$(UPNP_VERSION)
